name: 'Intelligo Actions'
description: 'Github actions for Intelligo Systems.'
author: 'Intelligo Systems'
inputs:
  packages: '["my-package"]'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: gray-dark